class InactiveCourseException extends  Exception{}
class DoublicateStudentException extends Exception{}
class DoublicateCourseException extends  Exception{}
class DoublicateTeacherException extends Exception{}
class NotFindCourseOfSemester extends Exception{}
class NotFindCurrentCourseException extends Exception{}
class InvalidCurseException extends  Exception{}
class NotFindStudentIdException extends  Exception{}
class DoublicateAssignmentException extends  Exception{}